services:
    MMCFosUserBundle.password_resetting:
        class: MMC\FosUserBundle\EventListener\PasswordResettingListener
        arguments: [ '@router' ]
        tags:
            - { name: kernel.event_subscriber }

    mmc_fos_user_bundle.sonata_admin.user:
        class: 'MMC\FosUserBundle\Admin\UserAdmin'
        arguments:
            - ~
            - 'MMC\FosUserBundle\Entity\User'
            - ~
        calls:
            - [ setTranslationDomain, [UserAdmin]]
            - [ setUserManager, [ '@fos_user.user_manager']]

    mmc_fos_user_bundle.sonata_admin.template:
        class: 'MMC\FosUserBundle\Block\UserBlock'
        arguments:
            - mmc_fos_user_bundle.sonata_admin.template
            - "@templating"
