services:
    MMCFosUserBundle.password_resetting:
        class: MMC\FosUserBundle\EventListener\PasswordResettingListener
        tags:
            - { name: kernel.event_subscriber }

    mmc_fos_user_bundle.sonata_admin.user:
        class: 'MMC\FosUserBundle\Admin\UserAdmin'
        arguments:
            - ~
            - 'MMC\FosUserBundle\Entity\User'
            - ~
        calls:
            - [ setTranslationDomain, [UserAdmin]]
            - [ setUserManager, [ '@fos_user.user_manager']]
            - [ setRoleHierarchy, [ '%security.role_hierarchy.roles%']]
            - [ setRolesAvailables, ['%mmc_fos_user_bundle.roles.availables%']]

    mmc_fos_user_bundle.sonata_admin.template:
        class: 'MMC\FosUserBundle\Block\UserBlock'
        arguments:
            - mmc_fos_user_bundle.sonata_admin.template
            - "@templating"
